# Generated by Django 4.2.3 on 2023-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.CharField(max_length=8)),
                ('Apassword', models.CharField(max_length=20)),
                ('Aname', models.CharField(max_length=10)),
                ('Aemail', models.CharField(max_length=100)),
            ],
        ),
    ]
