# Generated by Django 4.2.3 on 2023-11-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0002_aid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aid',
            new_name='Admin',
        ),
    ]
