# Generated by Django 4.2.3 on 2023-11-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0003_rename_aid_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
