# Generated by Django 4.2.3 on 2023-11-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.CharField(max_length=8)),
                ('Spassword', models.CharField(max_length=20)),
                ('Sname', models.CharField(max_length=10)),
                ('Sgender', models.CharField(max_length=2)),
                ('Semail', models.CharField(max_length=100)),
                ('Smajor', models.CharField(max_length=20)),
                ('Sgrade', models.CharField(max_length=5)),
            ],
        ),
    ]
