# Generated by Django 4.2.3 on 2023-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentId', models.CharField(max_length=10)),
                ('Sid', models.CharField(max_length=8)),
                ('Pid', models.CharField(max_length=10)),
                ('CommentContent', models.CharField(max_length=200)),
                ('CommentTime', models.DateTimeField()),
                ('CommentLikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommunityId', models.CharField(max_length=10)),
                ('CommunityName', models.CharField(max_length=20)),
                ('Aid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommunityId', models.CharField(max_length=10)),
                ('Sid', models.CharField(max_length=8)),
                ('ifAssist', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=10)),
                ('CourseName', models.CharField(max_length=20)),
                ('CourseType', models.CharField(max_length=10)),
                ('CourseDescription', models.CharField(max_length=200)),
                ('Aid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=10)),
                ('FName', models.CharField(max_length=20)),
                ('Faddr', models.CharField(max_length=200)),
                ('Ftime', models.DateTimeField()),
                ('CourseId', models.CharField(max_length=10)),
                ('Sid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iid', models.CharField(max_length=10)),
                ('Iname', models.CharField(max_length=30)),
                ('Iaddr', models.CharField(max_length=200)),
                ('Pid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.CharField(max_length=10)),
                ('Sid', models.CharField(max_length=8)),
                ('Ptitle', models.CharField(max_length=30)),
                ('Plabel', models.CharField(max_length=10)),
                ('Pcontent', models.CharField(max_length=500)),
                ('Ptime', models.DateTimeField()),
                ('CommunityId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.CharField(max_length=8)),
                ('Pid', models.CharField(max_length=10)),
            ],
        ),
    ]
