# Generated by Django 4.2.3 on 2023-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0007_alter_admin_aemail_alter_student_semail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Sgrade',
            field=models.IntegerField(null=True),
        ),
    ]
