# Generated by Django 4.2.3 on 2023-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0008_alter_student_sgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CommentId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='CommunityId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communitystudent',
            name='CommunityId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='Fid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Iid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='CommunityId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentpostlike',
            name='Pid',
            field=models.IntegerField(),
        ),
    ]
