# Generated by Django 4.2.3 on 2023-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0009_alter_comment_commentid_alter_comment_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Plabel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
