# Generated by Django 4.2.3 on 2023-11-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0012_post_plikes_alter_comment_commentlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='CommentTime',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Ftime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Ptime',
        ),
    ]
