# Generated by Django 4.2.3 on 2023-11-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0013_remove_comment_commenttime_remove_file_ftime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Aid',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='CommentId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Pid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='community',
            name='CommunityId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='communitystudent',
            name='CommunityId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='Fid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='Iid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='Pid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='CommunityId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='Pid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentpostlike',
            name='Pid',
            field=models.CharField(max_length=30),
        ),
    ]
