# Generated by Django 4.2.3 on 2023-11-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0014_alter_admin_aid_alter_comment_commentid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=1)),
                ('commentId', models.IntegerField(default=1)),
                ('fid', models.IntegerField(default=1)),
                ('communityId', models.IntegerField(default=1)),
                ('iid', models.IntegerField(default=1)),
                ('courseId', models.IntegerField(default=1)),
            ],
        ),
    ]
